name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'mysecretpassword'

      - name: install pnpm
        run: npm i -G pnpm

      - name: install packages
        run: pnpm i

      - name: Build
        run: npm run build

      - name: Run tests and generate coverage report
        run: npm test
