name: CI
on:
  push:
    branches:
      - master
      - database/postgres
  pull_request:
    branches:
      - master
      - database/postgres

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql db: 'testdb'
          postgresql user: 'testuser'
          postgresql password: 'testpassword'

      - name: Fetch dependencies    
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm test

      - name: Upload coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run coverage