name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql db: 'digi_dukaan'
          postgresql user: 'postgres'
          postgresql password: 'mysecretpassword'

      - name: install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Run tests and generate coverage report
        run: npm test
